  version: '3'

  services:
    php:
      container_name: lemp_php
      build: php/
      restart: unless-stopped
      volumes:
        - ./html/:/var/www/html
      expose:
        - "9000"
      depends_on:
        - db

    nginx:
      container_name: lemp_nginx
      image: nginx:stable-alpine
      restart: unless-stopped
      volumes:
        - ./html/:/var/www/html

        - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro

      ports:
        - "80:80"
        
    db:
      container_name: lemp_mariadb
      image: mariadb:latest
      restart: unless-stopped
      volumes:
        - ./mariadb/initdb/:/docker-entrypoint-initdb.d
        - ./mariadb/data/:/var/lib/mysql/
      environment:
        - MYSQL_ROOT_PASSWORD=1234
        - MYSQL_DATABASE=qrcode
        - MYSQL_USER=root
        - MYSQL_PASSWORD=1234

    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin:latest
      ports:
      - 3306:80
      environment:
      - PMA_HOST=db
      depends_on:
      - db


  networks:
    default:
      external:
        name:
          web_network


          
          